### ISSUE TITLE
r, g and b values are the same

### ISSUE THREAD

**Issue by robsalasco** [tricinel/svelte-chroma-picker#4]
Hi! I'm trying the component in my app but I'm receiving the same value for r, g, b variables. Can you help me please?

Thanks for your work!

**Comment by tricinel** [comment]
Hi @robsalasco, do you happen to have a link to somewhere I can easily reproduce your issue? Codesandbox or similar?

I'll check it out nevertheless, but if you can provide that, cuts down on some time for me :)

Thanks!

**Comment by robsalasco** [comment]
Hi @tricinel !
Try this https://svelte.dev/repl/0dc9659aaaf846e78c03aa7c28128ab3?version=3.38.2

**Comment by tricinel** [comment]
Yup, copy that! I can confirm it and I'm already looking into it :)

**Comment by tricinel** [comment]
@robsalasco FYI, this is happening because of hueless colors (white and black), see: https://github.com/gka/chroma.js/issues/64 for example.

chromajs will treat whites and blacks as having no Hue, which is correct, but at the same time it means we can't pick white and black (or grays for that matter) - which sucks. So I will work on that.

If you change your initial color to something with a hue, it will work fine. But, again, as soon as you pick a white, black or a gray, it will be broken again :(

**Comment by tricinel** [comment]
@robsalasco just published `1.1.1` which fixes this issue :) Please let me know if it works now 👍 

I'll end up refactoring a bit of the code in the near future, when I get some spare time.
